% -------------------------------------------------------------------
%  Generated by MATLAB on 28-Aug-2022 20:55:42
%  MATLAB version: 9.11.0.1873467 (R2021b) Update 3
% -------------------------------------------------------------------
saveVarsMat = load('matlab_m.mat');

accel_brake_Rq_data = saveVarsMat.accel_brake_Rq_data; % <20001x1 double> too many elements

accel_brake_Rq_t = saveVarsMat.accel_brake_Rq_t; % <20001x1 double> too many elements

accel_pt_Rq_data = saveVarsMat.accel_pt_Rq_data; % <20001x1 double> too many elements

accel_pt_Rq_t = saveVarsMat.accel_pt_Rq_t; % <20001x1 double> too many elements

accel_pt_limit = 1;

aero_airDensity = 1.225;

aero_dragArea_lat = 74.4;

aero_dragArea_lon = 10.4;

aero_dragCoeff_cw_lat = 0.185;

aero_dragCoeff_cw_lon = 0.439;

axle_load_bobtail = [6132 2628 0];

axle_load_empty = [5060 6000 4110];

axle_load_full = [5240 13280 16280];

brake_emerg_delay = 0.01;

brake_emerg_t_const = 0.2;

brake_emerg_threshold = 2.3;

brake_max_deceleration_mpss = -6;

brake_raise_delay = 0.85;

brake_reduce_delay = 0.25;

brake_t_const = 0.1;

clutch_t_open = 0.9;

control_mode_lat = 1;

control_mode_lon = 1;

engine_maxEngineTorque = 2373;

engine_scaleTorque = 0.85;

engine_torque_Rq_data = saveVarsMat.engine_torque_Rq_data; % <20001x1 double> too many elements

engine_torque_Rq_t = saveVarsMat.engine_torque_Rq_t; % <20001x1 double> too many elements

engine_torque_delay = 0;

engine_torque_gain = 1;

engine_torque_map_T = [1315 1315 1470 1625 1780 2065 2349 2373 2349 2241 ...
                       2089 1896 1753 1401 1049 872 0 0];

engine_torque_map_n = [0 600 667 733 800 882 965 1075 1167 1258 1350 1487 ...
                       1625 1762 1900 2000 2100 2400];

engine_torque_t_const = 0.1;

final_drive_transmission = 2.41;

friction_torque_map_T = [-129 -170 -223 -253 -298 -353 -449 -515.2];

friction_torque_map_n = [608 896 1200 1408 1600 1808 2208 2448];

front_wheel_ang_delay = 0.02;

front_wheel_ang_gain = 1;

front_wheel_ang_init_value = 0;

front_wheel_ang_t_const = 0.1;

front_wheel_angle_Rq_data = saveVarsMat.front_wheel_angle_Rq_data; % <20001x1 double> too many elements

front_wheel_angle_Rq_t = saveVarsMat.front_wheel_angle_Rq_t; % <20001x1 double> too many elements

gearbox_transmission = [14.93 11.673 9.024 7.056 5.628 4.4 3.393 2.653 ...
                        2.051 1.604 1.279 1];

has_trailer = 1;

init_cond_dpsi1 = 0;

init_cond_dpsi2 = 0;

init_cond_psi1 = 0;

init_cond_psi2 = 0;

init_cond_v_lon = 0;

init_cond_x1 = 0;

init_cond_y1 = 0;

init_curvature = 0.01;

init_curvature_Fc = 100;

init_curvature_Kd = 0;

init_curvature_Ki = 5;

init_curvature_Kp = 2;

init_v_lon_Fc = 100;

init_v_lon_Kd = 0;

init_v_lon_Ki = 500;

init_v_lon_Kp = 1000;

initialization_mode = 0;

lat_road_grade_pct_data = saveVarsMat.lat_road_grade_pct_data; % <2001x1 double> too many elements

lat_road_grade_pct_t = saveVarsMat.lat_road_grade_pct_t; % <2001x1 double> too many elements

n_gears = 12;

n_tires = [2 8 8];

parameters_available = true;

payload_factor = 1;

road_slope_pct_data = saveVarsMat.road_slope_pct_data; % <20001x1 double> too many elements

road_slope_pct_t = saveVarsMat.road_slope_pct_t; % <20001x1 double> too many elements

rpm_shift_down = 800;

scale_corn_stiff_front = 1;

scale_corn_stiff_rear = 1;

scale_corn_stiff_trailer = 1;

shiftup_map_rpm = ...
  [1350 1350 1350 1350 1350 1350 1350 1330 1300 1300 1300;
   1350 1350 1350 1350 1350 1350 1350 1330 1300 1300 1300;
   1640 1600 1500 1470 1450 1450 1350 1330 1300 1300 1300;
   2046 1952 1870 1750 1680 1620 1590 1560 1540 1510 1500;
   2080 1950 1900 1850 1800 1750 1700 1680 1650 1600 1550;
   2080 1950 1900 1850 1800 1750 1700 1680 1650 1600 1550;
   2080 1950 1900 1850 1800 1750 1700 1680 1650 1600 1550];

shiftup_map_trq_Rq = [0 200 500 1000 1500 2500 5000];

simpletruck_analyzer_results = saveVarsMat.simpletruck_analyzer_results; % <1x1 struct> too many elements at simpletruck_analyzer_results.time

simpletruck_res = saveVarsMat.simpletruck_res; % <1x1 Simulink.SimulationOutput> unsupported class

tire_c_alpha = [160000 150000 150000];

tire_relax_length = [0.5177 0.5177 0.5177];

tire_roll_resist = [0.007 0.007 0.007];

tire_static_radius = [0.475 0.51 0.475];

tractor_AxFr_to_AxRe1 = 5.17;

tractor_AxRe1_to_AxRe2 = 1.325;

tractor_AxReTwinTireFlag = true;

tractor_Front_to_AxFr = 1.1;

tractor_Izz = 55649;

tractor_Length = 8.429;

tractor_Width = 2.5;

tractor_lf = 2.585;

tractor_lk = 3.0975;

tractor_lr = 3.2475;

tractor_m = 8760;

tractor_refsys_to_rear_axle_center = 0;

tractor_tireRadius = 0.5;

tractor_tireWidth = 0.275;

tractor_twinTireDistance = 0.315;

tractor_wheelbase = 5.8325;

trailer_AxTr1_to_AxTr2 = 1.25;

trailer_Front_to_KingPin = 0.91;

trailer_Izz = 107407;

trailer_Izz_payload = 261401;

trailer_Length = 16.15;

trailer_Width = 2.5;

trailer_ltf = 8.14;

trailer_ltr = 3.425;

trailer_m = 6114;

trailer_m_payload = 21413;

trailer_refsys_to_hitch = 11.565;

trailer_tireRadius = 0.5;

trailer_tireWidth = 0.275;

trailer_twinTireDistance = 0.315;

trailer_twinTireFlag = true;

trailer_wheelbase = 11.565;

vehicle_mass = 36287;

wind_v_lat_data = saveVarsMat.wind_v_lat_data; % <2001x1 double> too many elements

wind_v_lat_t = saveVarsMat.wind_v_lat_t; % <2001x1 double> too many elements

wind_v_lon_data = saveVarsMat.wind_v_lon_data; % <2001x1 double> too many elements

wind_v_lon_t = saveVarsMat.wind_v_lon_t; % <2001x1 double> too many elements

clear saveVarsMat;
