# Copyright 2024 Mojtaba (Moji) Fathi

#  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”),
# to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

#  THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

load("//:pooya_rules.bzl", "pooya_cc_binary")

pooya_cc_binary(
    name = "gain_block",
    src = "gain_block.cpp",
)

pooya_cc_binary(
    name = "memory_block",
    src = "memory_block.cpp",
)

pooya_cc_binary(
    name = "delay_block",
    src = "delay_block.cpp",
)

pooya_cc_binary(
    name = "test03",
    src = "test03_integrator.cpp",
)

pooya_cc_binary(
    name = "test04",
    src = "test04_mass_spring.cpp",
)

pooya_cc_binary(
    name = "test05",
    src = "test05_pendulum.cpp",
)

pooya_cc_binary(
    name = "test06",
    src = "test06_pendulum_with_torque.cpp",
)

pooya_cc_binary(
    name = "test07",
    src = "test07_pendulum_with_pi.cpp",
)

pooya_cc_binary(
    name = "test08",
    src = "test08_pendulum_with_pid.cpp",
)

pooya_cc_binary(
    name = "test09",
    src = "test09_mass_spring_damper.cpp",
)

pooya_cc_binary(
    name = "test10",
    src = "test10_memory_with_bus.cpp",
)

pooya_cc_binary(
    name = "test11",
    src = "test11_int_gain.cpp",
)

pooya_cc_binary(
    name = "tutorial01",
    src = "tut01_mass_spring_damper.cpp",
)
