clear
bazel test //tests/... "$@"
bazel run //samples:gain_block "$@"
bazel run //samples:memory_block "$@"
bazel run //samples:delay_block "$@"
bazel run //samples:test03 "$@"
bazel run //samples:test04 "$@"
bazel run //samples:test05 "$@"
bazel run //samples:test06 "$@"
bazel run //samples:test07 "$@"
bazel run //samples:test08 "$@"
bazel run //samples:test09 "$@"
bazel run //samples:test10 "$@"
bazel run //samples:test11 "$@"
bazel run //samples:tutorial01 "$@"
