name: Tests Passed
on:
  push:

jobs:
  bazel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Bazel
      # uses: philwo/setup-bazel@v2
      uses: bazelbuild/setup-bazelisk@v3

    - name: Run Bazel Tests
      run: |
        bazel clean
        bazel test //... --enable_workspace --test_output=errors

